alias: 🌛 Awtrix Night Mode 🌛
description: ""
trigger:
  - platform: time
    at: "23:00:00"
    id: NM Start
    enabled: true
  - platform: time
    at: "06:00:00"
    id: NM End
    enabled: true
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - NM Start
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_434d94/switch
              payload: "{\"name\":\"Time\"}"
          - service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_434d94/settings
              payload: >-
                { "WD": false, "TIME_COL": [255,0,0], "TMODE": 0, "BRI": 1,
                "ABRI": false, "ATRANS": false }
      - conditions:
          - condition: trigger
            id:
              - NM End
            enabled: true
        sequence:
          - service: mqtt.publish
            data:
              qos: 0
              retain: false
              topic: awtrix_a8ba90/settings
              payload: >-
                { "WD": true, "TIME_COL": [255,255,255], "TMODE": 2,
                "ABRI": true, "ATRANS": true }
mode: single
